### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by timscott** [iltempo/sublime-text-2-hash-syntax#2]
When I install via Package Control in ST3, I get an error:

```
reloading Packages/User/Preferences.sublime-settings
reloading plugin Ruby 1.9 Hash Converter.HashSyntax
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1505, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1505, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1522, in _find_and_load_unlocked
ImportError: No module named 'Ruby 1'
found 12 files for base name Default.sublime-keymap
found 8 files for base name Main.sublime-menu
found 1 files for base name Default.sublime-theme
lib/inflector/languages/spanish.py in /Users/tscott/Library/Application Support/Sublime Text 3/Installed Packages/Simple Rails Navigator.sublime-package is not utf-8 encoded, unable to load plugin
libs/inflector/Rules/Spanish.py in /Users/tscott/Library/Application Support/Sublime Text 3/Installed Packages/SublimeCodeIntel.sublime-package is not utf-8 encoded, unable to load plugin
```

I installed ST3 just today, so it's the latest beta build.

**Comment by gsmetal** [comment]
I think, Package Control lost changes during refactoring their repositories system. https://github.com/iltempo/sublime-text-2-hash-syntax/issues/1#issuecomment-26973214

**Comment by thomasdarde** [comment]
A good way to install it is this one :
http://www.macdrifter.com/2012/08/install-sublime-packages-from-github.html

**Comment by mix86** [comment]
The problem in the package name. Python package name can not contain ".", and "Ruby 1.9 Hash Converter" contains one. I rename it to RubyHashConverter and it works fine!

Thanks to author!

**Comment by iltempo** [comment]
I sent a pull request to get that fixed.
https://github.com/wbond/package_control_channel/pull/3021
